language: node_js
node_js:
  - 'lts/dubnium'

before_script:
  - npm run test

script: npm run build

deploy:
  - provider: s3
    access_key_id: $DEPLOYER_ACCESS_KEY
    secret_access_key: $DEPLOYER_SECRET_KEY
    bucket: lorem.fabioaromanini.com
    skip_cleanup: true
    local_dir: build
    region: 'us-east-1'
    on:
      branch: deploy-config
