export default `Lorem ipsum dolor sit amet, consectetur adipiscing elit. In posuere tempor viverra. Sed felis ex, tincidunt nec iaculis quis, hendrerit sit amet nunc. Nullam ut maximus nibh, in bibendum nibh. Ut urna metus, molestie vel convallis ut, sollicitudin a ipsum. Aliquam tortor metus, euismod id ullamcorper eu, commodo sed justo. Sed et scelerisque nulla. Nam consectetur ante in mi blandit, elementum dictum lorem vehicula. Nulla in urna sed est bibendum semper. Curabitur pellentesque nisl dapibus mauris pretium, ut fringilla metus varius. In consequat tortor est, ac euismod eros placerat et. Fusce pellentesque nisl ex, ut scelerisque purus auctor tincidunt. Aenean efficitur enim quis lacus pharetra gravida. Praesent eget lacinia elit. Phasellus pulvinar ligula at quam efficitur laoreet. Curabitur et leo vestibulum, viverra urna ut, hendrerit sapien. Nunc sed sapien eget urna rutrum porta quis vitae nibh.

Donec a commodo tellus, vitae accumsan est. Sed pharetra egestas augue, quis aliquam tortor venenatis in. Proin eu metus vulputate, egestas enim eu, dignissim nulla. Nullam tristique lacus vel porta tincidunt. Maecenas rhoncus scelerisque purus vel ultricies. Pellentesque eleifend id sem ac interdum. Suspendisse nec enim in orci fermentum suscipit in vel ex. Phasellus ac congue dui. Nullam arcu erat, dignissim quis semper quis, gravida ac mi.

Nunc porttitor tempor magna, et congue augue faucibus non. Sed in mi id purus eleifend vestibulum. Curabitur convallis mattis nisl, quis rutrum risus. Morbi vulputate lectus non neque vulputate maximus. Ut aliquam nibh in suscipit suscipit. Curabitur vitae ullamcorper metus. Curabitur vulputate turpis dui, quis euismod neque aliquam vitae. Suspendisse porta egestas nisi, vitae consequat ligula lobortis non. Proin non iaculis dui. Ut interdum ac dui et convallis. Ut eget congue magna.

Etiam vel luctus eros. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla eleifend tincidunt rhoncus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus commodo porta dolor, id congue ligula. Pellentesque eget malesuada est, sed feugiat magna. Vestibulum venenatis mollis magna sit amet egestas. Donec malesuada maximus lacinia. Etiam vitae felis mollis, varius odio ac, elementum justo. Mauris consectetur vestibulum euismod. Fusce vitae maximus tortor.

Etiam in velit pharetra, varius dui et, hendrerit odio. Phasellus a commodo nibh. Curabitur eleifend mi elit, at varius erat suscipit non. Suspendisse egestas, nunc eget molestie posuere, dui nibh sollicitudin erat, vel commodo enim risus nec sem. Donec urna lacus, hendrerit in imperdiet a, euismod eget arcu. Maecenas aliquet tempor eros, ac consequat leo cursus ornare. Nam egestas massa nec quam mollis efficitur. Morbi vel mollis tellus, eu pellentesque enim. Vestibulum massa metus, fermentum ac laoreet ut, mattis ut libero. Nunc vitae ultrices ipsum, vitae pharetra urna. Nulla pharetra lacus nec ante pellentesque dictum. Vestibulum vel ex in lorem bibendum tempor sed eu arcu. Etiam dignissim, tortor eu consectetur porttitor, lectus libero placerat diam, vel hendrerit nunc dui et mi. Quisque sapien velit, semper eu egestas vitae, lobortis sit amet felis. Morbi convallis eros nunc.`;
